spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: 'TRUE'
        hibernate:
            ddl-auto: update
        open-in-view: 'false'
    mvc:
        hiddenmethod:
            filter:
                enabled: 'true'
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://localhost:3306/Explore_Local?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
        username: ${db_username}
        password: ${db_password}
    thymeleaf: # Thymeleaf
        cache: false
        mode: HTML
        encoding: UTF-8
        prefix: file:src/main/resources/templates/
    web:
        resources:
            static-locations: file:src/main/resources/static/
            cache:
                period: 0


explore_local:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:1234}
    remember.me.key: ${REMEMBER_ME_KEY:1234}

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor: TRACE
                SQL: DEBUG
            nodeValue: WARN
        blog: WARN
server:
    port: 8080
